import { ProviderType, StandardizedDailyMetric } from "./services/wearables/types";

export enum View {
  JOURNAL = "JOURNAL",
  DASHBOARD = "DASHBOARD",
  LIVE_COACH = "LIVE_COACH",
  SEARCH = "SEARCH",
  VISION = "VISION",
  BIO_MIRROR = "BIO_MIRROR",
  SETTINGS = "SETTINGS",
  GUIDE = "GUIDE",
  TERMS = "TERMS",
  ROADMAP = "ROADMAP",
  CLINICAL = "CLINICAL",
  BETA_DASHBOARD = "BETA_DASHBOARD",
}

export interface UserSettings {
  cycleStartDate?: string; // YYYY-MM-DD
  avgCycleLength?: number; // Default 28
  safetyContact?: string; // Phone number or Name for crisis support
  theme?: "light" | "dark" | "system";
}

export interface Medication {
  name: string;
  dosage: string;
  unit: string;
}

export interface Symptom {
  name: string;
  severity: number; // 1-10
}

export interface SleepData {
  duration: number; // hours
  quality: "Poor" | "Fair" | "Good" | "Excellent";
}

export interface CapacityProfile {
  focus: number; // Deep work / Hyperfocus
  social: number; // Interaction bandwidth
  structure: number; // Meetings / Admin tolerance
  emotional: number; // Caregiving / Processing
  physical: number; // Movement energy
  sensory: number; // Noise / Light tolerance
  executive: number; // Decision making
  [key: string]: number; // Index signature for dynamic access
}

export interface NeuroMetrics {
  spoonLevel: number; // Legacy aggregate (calculated average of profile)
  sensoryLoad: number; // 1-10 (Environmental intensity)
  contextSwitches: number; // Estimated count of role/task switches
  cycleDay?: number; // Menstrual/Hormonal cycle day
  capacity: CapacityProfile; // Phase 1: Multi-dimensional capacity
  maskingScore?: number; // 1-10 (Social masking effort)
}

export interface StrategyRecommendation {
  id: string;
  title: string;
  action: string;
  type: "REST" | "FOCUS" | "SOCIAL" | "SENSORY" | "EXECUTIVE";
  icon?: string;
  relevanceScore: number;
}

export interface HealthEntry {
  id: string;
  timestamp: string; // ISO string
  rawText: string;
  mood: number; // 1-5
  moodLabel: string;
  medications: Medication[];
  symptoms: Symptom[];
  tags: string[]; // Generic tags
  activityTypes: string[]; // Phase 1: #DeepWork, #Meeting, #Social, etc.
  strengths: string[]; // Character strengths (Curiosity, Zest, etc.)
  neuroMetrics: NeuroMetrics;
  sleep?: SleepData;
  notes: string;
  aiStrategies?: StrategyRecommendation[]; // Phase 3 AI Generated Strategies
  aiReasoning?: string; // Why the AI flagged what it did
  updatedAt?: string; // ISO string for sync conflict resolution

  // ✅ All objective observations (voice, photo, text)
  objectiveObservations?: ObjectiveObservation[];
}

export interface WearableDataPoint {
  id: string;
  date: string; // YYYY-MM-DD
  provider: ProviderType;
  syncedAt: string; // ISO
  metrics: StandardizedDailyMetric;
  rawSourceData?: unknown; // For debugging
}

export interface ChatMessage {
  id: string;
  role: "user" | "model";
  text: string;
  sources?: { uri: string; title: string }[];
}

export interface ParsedResponse {
  moodScore: number;
  moodLabel: string;
  medications: { name: string; amount: string; unit: string }[];
  symptoms: { name: string; severity: number }[];
  neuroMetrics: {
    environmentalMentions: string[];
    socialMentions: string[];
    executiveMentions: string[];
    physicalMentions: string[];
  };
  activityTypes: string[];
  strengths: string[];
  summary: string;
  strategies: StrategyRecommendation[];
  analysisReasoning: string;

  // ✅ Objective observations extracted from text
  objectiveObservations?: Observation[];

  // ✅ Gentle inquiry generated by AI
  gentleInquiry?: GentleInquiry;
}

export interface BurnoutForecast {
  riskLevel: "SUSTAINABLE" | "MODERATE" | "CRITICAL";
  score: number; // 0-100, where >80 is critical
  daysUntilCrash: number | null; // Prediction
  recoveryDaysNeeded: number;
  accumulatedDeficit: number; // Raw load score
  trend: "RISING" | "FALLING" | "STABLE";
  description: string;
}

export interface CyclePhaseContext {
  phase: "MENSTRUAL" | "FOLLICULAR" | "OVULATORY" | "LUTEAL";
  day: number;
  length: number;
  cognitiveImpact: string; // e.g. "High Focus", "Brain Fog Risk"
  energyPrediction: string;
  advice: string;
}

// State Check / Bio-Mirror Types

// FACS Action Unit - based on Ekman & Friesen's Facial Action Coding System
export interface ActionUnit {
  auCode: string; // "AU1", "AU4", "AU6", "AU12", "AU24", etc.
  name: string; // "Inner Brow Raiser", "Brow Lowerer", etc.
  intensity: "A" | "B" | "C" | "D" | "E"; // FACS intensity scale (A=trace, E=maximum)
  intensityNumeric: number; // 1-5 numeric equivalent
  confidence: number; // 0-1 detection confidence
}

// Key FACS Action Units for neurodivergent-relevant detection:
// AU1: Inner Brow Raiser (sadness, worry)
// AU4: Brow Lowerer (concentration, anger, distress)
// AU6: Cheek Raiser (genuine smile - Duchenne)
// AU7: Lid Tightener (concentration, squinting)
// AU12: Lip Corner Puller (smile)
// AU14: Dimpler (contempt, suppression)
// AU15: Lip Corner Depressor (sadness)
// AU17: Chin Raiser (doubt, sadness)
// AU24: Lip Pressor (tension, stress)
// AU43: Eyes Closed (fatigue)
// AU45: Blink (fatigue indicator when excessive)

export interface FacialAnalysis {
  confidence: number; // 0-1, overall confidence in analysis

  // NEW: Structured FACS Action Unit detection
  actionUnits: ActionUnit[];

  // NEW: FACS-based interpretation
  facsInterpretation?: {
    duchennSmile: boolean; // AU6 + AU12 = genuine smile
    socialSmile: boolean; // AU12 without AU6 = posed/social smile
    maskingIndicators: string[]; // Signs of emotional suppression
    fatigueIndicators: string[]; // AU43, excessive AU45, ptosis
    tensionIndicators: string[]; // AU4, AU24, jaw tension
  };

  // General observations (backward compatible)
  observations: Array<{
    category: "tension" | "fatigue" | "lighting" | "environmental";
    value: string;
    evidence: string;
  }>;
  lighting: string;
  lightingSeverity: "low" | "moderate" | "high";
  environmentalClues: string[];

  // Legacy fields for backward compatibility
  jawTension?: number; // 0-1, derived from AU4, AU24
  eyeFatigue?: number; // 0-1, derived from AU43, ptosis detection
  primaryEmotion?: string;
  signs?: Array<{ description: string; confidence: number }>;
}

// New: Baseline Calibration for Bio-Mirror
export interface FacialBaseline {
  id: string;
  timestamp: string;
  neutralTension: number; // Resting jaw tension
  neutralFatigue: number; // Resting eye openness
  neutralMasking: number; // Resting asymmetry
}

export interface StateCheck {
  id: string;
  timestamp: string;
  imageBase64?: string; // Optional (if saved)
  analysis: FacialAnalysis;
  userNote?: string;
}

// ============================================
// Journal Entry Enhancement V2: Objective Observations
// ============================================

export interface Observation {
  category: "lighting" | "noise" | "tension" | "fatigue" | "speech-pace" | "tone";
  value: string; // "bright fluorescent", "moderate background noise"
  severity: "low" | "moderate" | "high";
  evidence: string; // "detected in photo", "measured in audio"
}

export interface ObjectiveObservation {
  type: "visual" | "audio" | "text";
  source: "bio-mirror" | "voice" | "text-input";
  observations: Observation[];
  confidence: number;
  timestamp: string;
}

export interface GentleInquiry {
  id: string;
  basedOn: string[]; // ["lighting detected", "user mentioned 'harsh'"]
  question: string; // "How is that lighting affecting you?"
  tone: "curious" | "supportive" | "informational";
  skipAllowed: boolean; // Always true
  priority: "low" | "medium" | "high";
}

export interface PatternInsight {
  observation: string; // "Your sensory tolerance is 6/10"
  context: string; // "Compared to typical range (4-7)"
  insight: string; // "Your sensory regulation is working efficiently"
  question?: string; // "What helps you with bright environments?"
}

export interface CapacityCalibration {
  dimension: keyof CapacityProfile;
  informedBy: string[]; // ["audio: calm speech", "text: 'feeling great'"]
  suggestedValue: number;
  userAdjustable: boolean;
  confidence: number;
}

export interface ConversationTurn {
  id: string;
  role: "mae" | "user";
  content: string;
  timestamp: string;
  signalsDetected?: Observation[];
  inquiry?: GentleInquiry;
}

export interface JournalStage {
  stage: 1 | 2 | 3 | 4;
  completed: boolean;
  data: Partial<HealthEntry>;
  timestamp: string;
}

export interface JournalSession {
  sessionId: string;
  startTime: string;
  currentStage: 1 | 2 | 3 | 4;
  captureMethod: "bio-mirror" | "voice" | "text";
  observations: ObjectiveObservation[];
  conversationHistory: ConversationTurn[];
  capacityCalibrations: CapacityCalibration[];
  partialEntry: Partial<HealthEntry>;
}
